"""Review-first source parsers and data contracts."""

from windsor_widget.imports.contracts import SOURCE_CONTRACTS, SourceContract
from windsor_widget.imports.matching import (
    CustomerGroupProposal,
    CustomerPriceFileProposal,
    ItemSupplierProposal,
    MatchAlternative,
    PriceFileReference,
    PurchaseEvidence,
    load_customer_price_file_references,
    most_recent_purchase_by_item,
    propose_customer_groups,
    propose_customer_price_file_matches,
    propose_item_supplier_matches,
)
from windsor_widget.imports.myob_text import (
    MyobFileInspection,
    ParsedFile,
    ParsedRow,
    ParseIssue,
    inspect_myob_text,
    iter_myob_rows,
    parse_myob_text,
)
from windsor_widget.imports.pipeline import (
    PipelineSummary,
    SourceFileRequest,
    SourceFileResult,
    SourceManifestError,
    inspect_source_files,
    load_source_manifest,
    run_import_pipeline,
    stage_source_files,
    write_pipeline_report,
)
from windsor_widget.imports.staging import (
    DuplicateImportBatchError,
    StagingSummary,
    stage_myob_file,
)

__all__ = [
    "MyobFileInspection",
    "ParsedFile",
    "ParsedRow",
    "ParseIssue",
    "PipelineSummary",
    "SOURCE_CONTRACTS",
    "SourceContract",
    "SourceFileRequest",
    "SourceFileResult",
    "SourceManifestError",
    "DuplicateImportBatchError",
    "CustomerGroupProposal",
    "CustomerPriceFileProposal",
    "ItemSupplierProposal",
    "MatchAlternative",
    "PriceFileReference",
    "PurchaseEvidence",
    "StagingSummary",
    "inspect_myob_text",
    "inspect_source_files",
    "iter_myob_rows",
    "load_customer_price_file_references",
    "load_source_manifest",
    "most_recent_purchase_by_item",
    "parse_myob_text",
    "propose_customer_groups",
    "propose_customer_price_file_matches",
    "propose_item_supplier_matches",
    "run_import_pipeline",
    "stage_myob_file",
    "stage_source_files",
    "write_pipeline_report",
]
